//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConNhaNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string ID { get; set; }
        public string list { get; set; }
        public string amount { get; set; }
        public string ID_cart { get; set; }
    
        public virtual User User { get; set; }
    }
}
