//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConNhaNong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.Reports = new HashSet<Report>();
        }

        [StringLength(30)]
        public string ID { get; set; }

        public double? price { get; set; }

        public int? amount { get; set; }

        [StringLength(100)]
        [Display(Name = "Tên sản phẩm")]
        public string name_product { get; set; }

        [StringLength(2000)]
        public string file_names { get; set; }

        [StringLength(1000)]
        public string Descriptions { get; set; }
        [StringLength(50)]

        public string product_category { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
