//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConNhaNong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public string id_product { get; set; }
        public string Email_send { get; set; }
        public string Notes { get; set; }
        public string Status_report { get; set; }
    
        public virtual product product { get; set; }
    }
}
